import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/lib/redux/Provider";


/* const geistSans = Geist({variable: "--font-geist-sans", subsets: ["latin"]});
const geistMono = Geist_Mono({variable: "--font-geist-mono",subsets: ["latin"]});
${geistSans.variable} ${geistMono.variable}  */


export const metadata: Metadata = {
  title: "CLORR",
  description: "Generated by create next app",
};

export default function RootLayout( {children,}: Readonly<{children: React.ReactNode}>) {

  return (
    <html lang="en">
      <body className={`antialiased bg-black2 text-cyan flex flex-col justify-between tracking-[.1rem] leading-none min-h-screen`}>
        <ReduxProvider>
          <Navbar></Navbar>
          <div className="grow">
              {children}
          </div>
          <Footer></Footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
